curl --location --request PUT 'http://localhost:8000/api/users/1' \
--form 'employeeId=99' \
--form 'employeeName=Update Ilyas' \
--form 'employeeGender=male' \
--form 'employeeBirthDate=31414141' \
--form 'employeePhoneNumber=12345678' \
--form 'employeeEmail=testupdate@gmail.com' \
--form 'employeeRoleId=1' \
--form 'employeeDepartmentId=1' \
--form 'employeeShiftId=1' \
--form 'employeeWorkLocationId=1' \
--form 'employeePassword=updatepassword' \
--form 'employeeWhatsApp=1231312' \
--form 'employeeLinkedin=iaika' \
--form 'employeeTelegram=32131312' \
--form 'employeeBiography=bio' \
--form 'accountStatus=1' \
--form 'profilePhoto=@C:/Users/andik/OneDrive/Gambar/dwada.png'
